// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4ElNw5traGl_5cu_SI1cENXKGHEFVLM',
    appId: '1:833776742151:web:4310931bced9b4782d9fa2',
    messagingSenderId: '833776742151',
    projectId: 'paklan-45c3c',
    authDomain: 'paklan-45c3c.firebaseapp.com',
    storageBucket: 'paklan-45c3c.firebasestorage.app',
    measurementId: 'G-Q0Q9RCKX51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBItNocNsmgnfV-HmdvOEQADRXoMZ_1Y',
    appId: '1:833776742151:android:c91e58fe4c6eb22c2d9fa2',
    messagingSenderId: '833776742151',
    projectId: 'paklan-45c3c',
    storageBucket: 'paklan-45c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKB7cnsrujIaO5PLvt6SZQeckg_aLUu8',
    appId: '1:833776742151:ios:42e1fde3755433ce2d9fa2',
    messagingSenderId: '833776742151',
    projectId: 'paklan-45c3c',
    storageBucket: 'paklan-45c3c.firebasestorage.app',
    iosBundleId: 'com.example.packlanAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgKB7cnsrujIaO5PLvt6SZQeckg_aLUu8',
    appId: '1:833776742151:ios:42e1fde3755433ce2d9fa2',
    messagingSenderId: '833776742151',
    projectId: 'paklan-45c3c',
    storageBucket: 'paklan-45c3c.firebasestorage.app',
    iosBundleId: 'com.example.packlanAlpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm4ElNw5traGl_5cu_SI1cENXKGHEFVLM',
    appId: '1:833776742151:web:ac24e09d0bad48f62d9fa2',
    messagingSenderId: '833776742151',
    projectId: 'paklan-45c3c',
    authDomain: 'paklan-45c3c.firebaseapp.com',
    storageBucket: 'paklan-45c3c.firebasestorage.app',
    measurementId: 'G-2LQY24T5WP',
  );

}